name: Push - Create & Tag Protobuf - Go

on:
  push:
    branches:
      - "main"

jobs:
  generate-protobuf-go:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.21"
          check-latest: false
          cache: true
      - name: Install Dependencies
        run: |
          sudo apt-get install -y protobuf-compiler golang-goprotobuf-dev
          go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
      - name: Generate Go Source
        shell: bash
        run: |
          make build
      - name: Commit generated files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore(protobuf-go) : Auto-generated by Github Action"
          tagging_message: ${{ steps.tag_version.outputs.new_tag }}
          file_pattern: "protogen/*"
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
